IDS, = glob_wildcards("resources/{id}.bam") # Bam files to iterate across

rptFiles          = "results/{sample}.txt"
all_results = expand([rptFiles], sample = IDS)

rule all:
    input:
        all_results
    output:
        summary = "results/summary.rpt",
    shell:
        "workflow/scripts/summarise results/*.txt > {output.summary}"

#
#################### Matt's flow ###########################
rule determineSex:
    input:
        bam = "resources/{sample}.bam",
    output:
        report = "results/{sample}.txt",
    shell:
        "workflow/scripts/sex_please {input.bam} > {output.report}"
